# Site settings
baseurl = "https://happy-mclean-a98d38.netlify.com/"
languageCode = "en-us"
title = "static template cedille"
theme = "syna"
enableGitInfo = true
version = "0.15.0"
publishDir = "public"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

# Google Analytics tracking
googleAnalytics = ""

[params]
  name = "Okkur Labs"
  description = "Open Source Theme for your next project"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/apropos"
  name = "A Propos"
  weight = 20

[[menu.main]]
  url = "#members"
  name = "Members"
  weight = 30

[[menu.main]]
  url = "#portfolio"
  name = "Projets"
  weight = 40

[[menu.main]]
  url = "#partenaires"
  name = "Partenaires"
  weight = 50

[[menu.main]]
  url = "#contact"
  name = "Contact"
  weight = 60

[[menu.footer]]
  url = "/apropos"
  name = "A Propos"
  weight = 10

[[menu.footer]]
  url = "#portfolio"
  name = "Projets"
  weight = 30

[[menu.copyright_footer]]
  url = "/apropos"
  name = "A Propos"
  weight = 10

[[menu.copyright_footer]]
  url = "#"
  name = "Another Link"
  weight = 30

[[menu.footer_social]]
  weight = 20
  name = "facebook"
  pre = "fab fa-facebook-f"
  url = "#"

[[menu.footer_social]]
  weight = 30
  name = "linkedin"
  pre = "fab fa-linkedin-in"
  url = "#"
